name: Build WebRTC SDK

on:
  workflow_dispatch:  # 手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your forked source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 curl build-essential unzip pkg-config ninja-build clang

    - name: Download GN
      run: |
        git clone https://gn.googlesource.com/gn
        cd gn
        python3 build/gen.py
        ninja -C out
        echo "$PWD/out" >> $GITHUB_PATH

    - name: Generate build config
      run: |
        gn gen out/Default --args='is_debug=false rtc_include_tests=false treat_warnings_as_errors=false use_custom_libcxx=false'

    - name: Build WebRTC static lib
      run: |
        ninja -C out/Default

    - name: Archive headers
      run: |
        mkdir -p out/Default/include
        find . -type f -name '*.h' -not -path './.git/*' -exec cp --parents {} out/Default/include/ \;

    - name: Upload full SDK (lib + headers)
      uses: actions/upload-artifact@v4
      with:
        name: webrtc-sdk
        path: |
          out/Default/*.a
          out/Default/include/
